### ISSUE TITLE
erhmmmmmmm....

### ISSUE THREAD

**Issue by xAzz** [iiali/Mubox-v5#1]
_cough_ you can't code.

**Comment by iiali** [comment]
i'm not coder but i have codes$ :)

**Comment by xAzz** [comment]
Sadly you got the code from my site rofl

**Comment by iiali** [comment]
i got it from this link
this your ?
https://storage.googleapis.com/mubox/V5/index.html

**Comment by xAzz** [comment]
Them faggots took it from my site lmao.

**Comment by xAzz** [comment]
Lol nah I don't care, it's shit code anyway
